# Docker Compose with MySQL Server
version: '3.3'
services:
  database:
    image: 'mysql:8'
    cap_add:
      - SYS_NICE
    container_name: '${APP_NAME}_mysql'
    hostname: '${APP_NAME}_mysql'
    networks:
        - internal
    ports:
        - '127.0.0.1:${DB_PORT}:3306'
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - mysql:/var/lib/mysql
    environment:
        MYSQL_EXPOSE_PORT: '${DB_PORT}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_USER: '${DB_USER}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'

  mongodb:
    image: mongo:3.7.1
    container_name: '${APP_NAME}_mongodb'
    networks:
        - internal
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
        MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
        - "27017:27017"
    volumes:
        - mongoDB:/data/db

volumes:
    mysql:
    mongoDB:

networks:
    internal: